require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to test the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator. If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails. There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.

RSpec.describe "/promotions", type: :request do
  # This should return the minimal set of attributes required to create a valid
  # Promotion. As you add validations to Promotion, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) do
    {
      code: "ASDAS",
      ends_at: (Time.zone.now + 2.days)
    }
  end

  let(:invalid_attributes) do
    {
      code: nil,
      ends_at: nil
    }
  end

  describe "GET /index" do
    it "renders a successful response" do
      Promotion.create! valid_attributes
      get promotions_url
      expect(response).to be_successful
    end
  end

  describe "GET /show" do
    it "renders a successful response" do
      promotion = Promotion.create! valid_attributes
      get promotion_url(promotion)
      expect(response).to be_successful
    end
  end

  describe "GET /new" do
    it "renders a successful response" do
      get new_promotion_url
      expect(response).to be_successful
    end
  end

  describe "GET /edit" do
    it "renders a successful response" do
      promotion = Promotion.create! valid_attributes
      get edit_promotion_url(promotion)
      expect(response).to be_successful
    end
  end

  describe "POST /create" do
    context "with valid parameters" do
      it "creates a new Promotion" do
        expect do
          post promotions_url, params: { promotion: valid_attributes }
        end.to change(Promotion, :count).by(1)
      end

      it "redirects to the created promotion" do
        post promotions_url, params: { promotion: valid_attributes }
        expect(response).to redirect_to(promotion_url(Promotion.last))
      end
    end

    context "with invalid parameters" do
      it "does not create a new Promotion" do
        expect do
          post promotions_url, params: { promotion: invalid_attributes }
        end.to change(Promotion, :count).by(0)
      end

      it "renders a response with 422 status (i.e. to display the 'new' template)" do
        post promotions_url, params: { promotion: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "PATCH /update" do
    context "with valid parameters" do
      let(:ten_days) { Time.now + 10.days }
      let(:new_attributes) do
        {
          code: "TAM",
          ends_at: ten_days
        }
      end

      it "updates the requested promotion" do
        promotion = Promotion.create! valid_attributes
        patch promotion_url(promotion), params: { promotion: new_attributes }
        promotion.reload

        expect(promotion.ends_at.day).to be(ten_days.day)
      end

      it "redirects to the promotion" do
        promotion = Promotion.create! valid_attributes
        patch promotion_url(promotion), params: { promotion: new_attributes }
        promotion.reload
        expect(response).to redirect_to(promotion_url(promotion))
      end
    end

    context "with invalid parameters" do
      it "renders a response with 422 status (i.e. to display the 'edit' template)" do
        promotion = Promotion.create! valid_attributes
        patch promotion_url(promotion), params: { promotion: invalid_attributes }
        expect(response).to have_http_status(:unprocessable_entity)
      end
    end
  end

  describe "DELETE /destroy" do
    it "destroys the requested promotion" do
      promotion = Promotion.create! valid_attributes
      expect do
        delete promotion_url(promotion)
      end.to change(Promotion, :count).by(-1)
    end

    it "redirects to the promotions list" do
      promotion = Promotion.create! valid_attributes
      delete promotion_url(promotion)
      expect(response).to redirect_to(promotions_url)
    end
  end
end
